apiVersion: apps/v1
kind: Deployment
metadata:
  name: polling-app
spec:
  template:
    spec:
      containers:
      - name: polling-app
        env:
        - name: ENVIRONMENT
          value: "dev"
